image: mutt/ubuntu:16.04

stages:
  - build

build:
  stage: build
  script:
    - ./prepare --disable-dependency-tracking --enable-gpgme --enable-sidebar --enable-compressed --enable-pop --enable-imap --enable-smtp --enable-debug --enable-hcache
    - make -j
